### ISSUE TITLE
Cannot compile error

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TF-LibsDisguises#1]
So, here is the error I currently get when you compile an unmodified version of TF-LibsDisguises:
`Failed to execute goal on project LibsDisguises: Could not resolve dependencies for project LibsDisguises:LibsDisguises:jar:9.0.9: Could not find artifact org.spigotmc:spigot-api:jar:1.10-R0.1-SNAPSHOT in dmulloy2-repo (http://repo.dmulloy2.net/content/groups/public/) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

That means that is cannot find the Spigot jar in the repo, I have fixed the issue by attaching the jar locally, but maybe this should be fixed in the code to allowed this?

**Comment by ghost** [comment]
@Wild1145 This is not a help wanted, I know how to solve the problem, I am saying this needs to be changed on github (i.e. removal of the repo path and addition of a local jar.)

**Comment by ghost** [comment]
@Wild1145 ?

**Comment by lemonsked** [comment]
Fixed @Commodore64x
