### ISSUE TITLE
Change /disguiseentity so it can't be used on other players.

### ISSUE THREAD

**Issue by MKVollmer25** [TotalFreedom/TF-LibsDisguises#2]
This suggestion is my response to [this thread](http://totalfreedom.boards.net/thread/48104/block-disguiseentity?page=1&scrollTo=549355). I can see how disguiseentity can be used for trolling, but like windows said, there are some creative uses in it. So, it should only be usable on mobs, and not players.

**Comment by lemonsked** [comment]
Already fixed.
